---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: raw-kuma-tls-general
  namespace: kuma-system
spec:
  commonName: kuma-tls-general-cert
  secretName: raw-kuma-tls-general
  duration: 8760h # 1 year
  renewBefore: 360h # 15d
  subject:
    organizations:
      - kuma
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - digital signature
    - key encipherment
    - server auth
    - client auth
  dnsNames:
    - kuma-control-plane.kuma-system
    - kuma-control-plane.kuma-system.svc
  issuerRef:
    name: kuma-ca-issuer
    kind: Issuer
    group: cert-manager.io
